import { Router } from "express";
import { jobsRouter } from "./jobs";
import { pagesRouter } from "./pages";
import { domainsRouter } from "./domains";
import { webhooksRouter } from "./webhooks";
import { statsRouter } from "./stats";
import { healthRouter } from "./health";
import { extractRouter } from "./extract";
import { agentRouter } from "./agent";
import { watchRouter } from "./watch";
import { failuresRouter } from "./failures";
import { extractionsRouter } from "./extractions";
import { activityRouter } from "./activity";
import { usageRouter } from "./usage";
import { receiptsRouter } from "./receipts";

export const crawlXV2Router = Router();

crawlXV2Router.use("/jobs", jobsRouter);
crawlXV2Router.use("/pages", pagesRouter);
crawlXV2Router.use("/domains", domainsRouter);
crawlXV2Router.use("/webhooks", webhooksRouter);
crawlXV2Router.use("/stats", statsRouter);
crawlXV2Router.use("/health", healthRouter);
crawlXV2Router.use("/extract", extractRouter);
crawlXV2Router.use("/agent", agentRouter);
crawlXV2Router.use("/watch", watchRouter);
crawlXV2Router.use("/failures", failuresRouter);
crawlXV2Router.use("/extractions", extractionsRouter);
crawlXV2Router.use("/activity", activityRouter);
crawlXV2Router.use("/usage", usageRouter);
crawlXV2Router.use("/receipts", receiptsRouter);
